### PR TITLE
corrections & features

### PR DESCRIPTION
**Pull request by GreatestOfAllTimee**
### Corrections:

- Comparison operator like `-g` or `>` only valid for _integer_ doesn't not require
  quote but still works fine if we add quote.

- Same as above but we should treat _strings_ with quote.

> Yes we can add quote (`""`) on _integer_ and without quote on _strings_
but this only for good practices.

### Features:

This only minor feat which we can handle user input properly.

### Breaking Changes?
No

### CODE REVIEW

**Review by abidarwish — APPROVED** [review]

**Review by abidarwish — APPROVED** [review]

**Review by abidarwish — APPROVED** [review]

**Review by abidarwish — APPROVED** [review]

**Review by abidarwish — APPROVED** [review]

**Review by abidarwish — APPROVED** [review]

**Review by abidarwish — APPROVED** [review]

**Review by abidarwish — APPROVED** [review]

**Comment by abidarwish** [comment]
I'm still learning and are familiarising with CLI. I have no formal education in programming and coding. Need more insight like yours to improve my script.

Thanks a lot.

**Comment by abidarwish** [comment]
I have no idea how to merge your commit into the main branch. Still new with GitHub workflow.

**Comment by GreatestOfAllTimee** [comment]
Hi! Thank you for approve this minor changes. I believe youre not familiar how to revert commit and resolve merge conflic. I will get into it when I get home soon.

It would be better if you can revert your commit 7898797d9935e24a91dc3aac616a5d7df73b6adc and 78614be1e93bd05859e2e65f3b13df5201d0d684 otherwise it gonna be more complex

**Comment by GreatestOfAllTimee** [comment]
you can try to merge this again, see if there is any conflict

**Pull request merged**
